
POST http://localhost:3000/api/v1/users
content-type: application/json

{
	"first_name": "admin2",
	"last_name":"nister2",
	"email": "admin2@admin.com",
	"password":"1234",
	"token": "",
	"active": true
}



###
POST https://example.com/comments 
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST http://localhost:3000/api/v1/users
content-type: application/json

{
	"first_name": "test2",
	"last_name":"valencia",
	"email": "shecho2@shecho.com",
	"password":"1234",
	"token": "",
	"active": true
}



###
GET http://localhost:3000/


###

POST http://localhost:3000/api/v1/users
content-type: application/json

{
	"first_name": "admin",
	"last_name":"nisters",
	"email": "admin@admin.com",
	"password":"1234",
	"token": "",
	"active": true
}


//login



###
POST http://localhost:3000/api/v1/users/login 

{
"email": "admin@admin.com",
	"password":"1234"
}

content


###
DELETE http://localhost:3000/api/v1/users/6
Authorization: token xxx